# Generated by Django 4.0.2 on 2022-02-21 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('youtube_search_api', '0001_initial'), ('youtube_search_api', '0002_queryresult_channel_name_queryresult_publish_time')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('channel_name', models.CharField(default=1, max_length=100)),
                ('publish_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
