# Generated by Django 4.0.2 on 2022-02-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
