# Generated by Django 4.0.2 on 2022-02-21 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_search_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresult',
            name='channel_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queryresult',
            name='publish_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
