# Generated by Django 4.0.2 on 2022-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_search_api', '0001_squashed_0002_queryresult_channel_name_queryresult_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryresult',
            name='channel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='queryresult',
            name='publish_time',
            field=models.DateField(),
        ),
    ]
